### ISSUE TITLE
Verify Routes from Dijkstras Algorithm

### ISSUE THREAD

**Issue by MoKob** [MoKob/ProjectX#12]
# Background

The merge of https://github.com/MoKob/ProjectX/pull/11 introduces Dijkstras algorithm to compute shortest paths. So far the testing only covers the general progress of the algorithm.

# Aim

To improve the quality of the test-suite, the verification should also analyze the full path (and distances) to verify unpacking / path-search.

# Tasks

 - [ ] test edges along path
 - [ ] test weights along path
 - [ ] test offsets and their influence on shortest paths

All tasks should cover both the single source, single target and the the multi-source, multi-target version of the algorithms.
